    version: '3'

    services:
      redis:
        image: redis
        command: redis-server --appendonly yes
        volumes:
          - ./data:/data
        ports:
          - 6379:6379
          
      clickcount:
        image: tomcat:8
        restart: unless-stopped
        volumes:
           - "/var/lib/jenkins/workspace/clickCount/target/clickCount.war:/usr/local/tomcat/webapps/clickCount.war"
        depends_on:
          - redis
        links:
          - redis
        ports:
          - 8088:8080
